### PR TITLE
added ascii alias for cat emoticon

### PR DESCRIPTION
**Pull request by Haz111**
@RocketChat/core 

After writing " :3 " chat will show cat emoticon

### CODE REVIEW

**Comment by ukasiu** [comment]
@Haz111 are you sure this file is not a generated asset?

**Comment by Haz111** [comment]
@ukasiu @kruczjak comment in this file says:

/**
- update emojuList variable with the most recent emojione release then
- run: node generaEmojiIndex.js
- grab the results and put into emojiPicker.js file
  */

so it looks like hand copied from https://github.com/Ranks/emojione/blob/master/emoji.json

**Comment by kruczjak** [comment]
👍 ok, will see when merging new versions :P

**Comment by kruczjak** [comment]
To sum up:

It doesn't work :/

**Pull request merged**
